workloads:
  api:
    spec:
      apiVersion: score.dev/v1b1
      containers:
        api:
          image: ghcr.io/outernet-foundation/placeframe/api:tree-35ba0e139f65717c5e3dfbac92949defc4cb2dfc
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          variables:
            AUTH_AUDIENCE: ${resources.config.auth_audience}
            AUTH_CERTS_URL: ${resources.auth.certs_url}
            AUTH_ISSUER_URL: ${resources.config.auth_issuer_url}
            AUTH_MODE: ${resources.config.auth_mode}
            AUTH_TOKEN_URL: ${resources.config.auth_token_url}
            AUTH_URL: ${resources.config.auth_url}
            DATABASE_API_USER: ${resources.db.api_username}
            DATABASE_API_USER_PASSWORD: ${resources.db.api_password}
            DATABASE_AUTH_USER: ${resources.db.auth_username}
            DATABASE_AUTH_USER_PASSWORD: ${resources.db.auth_password}
            DATABASE_NAME: ${resources.db.name}
            DATABASE_ORCHESTRATION_USER: ${resources.db.orchestration_username}
            DATABASE_ORCHESTRATION_USER_PASSWORD: ${resources.db.orchestration_password}
            DEPLOYMENT_ENVIRONMENT: ${resources.config.deployment_environment}
            LOCALIZER_CONTAINER_URL: http://localhost:8000
            LOKI_URL: http://localhost:3100
            POSTGRES_HOST: ${resources.db.host}
            PUBLIC_URL: ${resources.config.public_url}
            RECONSTRUCTIONS_BUCKET: ${resources.bucket.bucket}
            S3_ACCESS_KEY: ${resources.bucket.access_key_id}
            S3_ENDPOINT_URL: ${resources.bucket.endpoint}
            S3_SECRET_KEY: ${resources.bucket.secret_key}
      metadata:
        name: api
      resources:
        auth:
          id: placeframe-keycloak
          type: placeframe-keycloak
        bucket:
          id: placeframe-bucket
          type: s3
        config:
          id: placeframe-config
          type: placeframe-config
        db:
          id: placeframe-db
          type: placeframe-postgres
      service:
        ports:
          http:
            port: 8000
            targetPort: 8000
    file: api.yaml
    instance_suffix: -03400ec588
  gateway:
    spec:
      apiVersion: score.dev/v1b1
      containers:
        gateway:
          image: ghcr.io/outernet-foundation/placeframe/gateway:tree-4714e22b2bbd09351eef51bfe3b3c24bf483a33b
          variables:
            AUTH_MODE: ${resources.config.auth_mode}
            PUBLIC_URL: ${resources.config.public_url}
      metadata:
        name: gateway
      resources:
        config:
          id: placeframe-config
          type: placeframe-config
      service:
        ports:
          gateway:
            port: 8443
            targetPort: 8443
    file: gateway.yaml
    instance_suffix: -7b9d446cd8
  lease-server:
    spec:
      apiVersion: score.dev/v1b1
      containers:
        lease-server:
          image: ghcr.io/outernet-foundation/placeframe/lease-server:tree-c19874616f3264dcdc155617be3fb73de6c94e5a
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          variables:
            DATABASE_NAME: ${resources.db.name}
            DATABASE_ORCHESTRATION_USER: ${resources.db.orchestration_username}
            DATABASE_ORCHESTRATION_USER_PASSWORD: ${resources.db.orchestration_password}
            DEPLOYMENT_ENVIRONMENT: development
            POSTGRES_HOST: ${resources.db.host}
      metadata:
        name: lease-server
      resources:
        db:
          id: placeframe-db
          type: placeframe-postgres
      service:
        ports:
          http:
            port: 8000
            targetPort: 8000
    file: lease-server.yaml
    instance_suffix: -97427824b2
resources:
  placeframe-config.default#placeframe-config:
    guid: a01d1004-f196-476f-28a6-6c8e379d5896
    type: placeframe-config
    class: default
    id: placeframe-config
    metadata: {}
    params: {}
    source_workload: api
    provisioner: template://placeframe/config-k8s
    state: {}
    outputs:
      auth_audience: "\U0001F510\U0001F4ACplaceframe-secrets_AUTH_AUDIENCE\U0001F4AC\U0001F510"
      auth_issuer_url: "\U0001F510\U0001F4ACplaceframe-secrets_AUTH_ISSUER_URL\U0001F4AC\U0001F510"
      auth_mode: "\U0001F510\U0001F4ACplaceframe-secrets_AUTH_MODE\U0001F4AC\U0001F510"
      auth_token_url: "\U0001F510\U0001F4ACplaceframe-secrets_AUTH_TOKEN_URL\U0001F4AC\U0001F510"
      auth_url: "\U0001F510\U0001F4ACplaceframe-secrets_AUTH_URL\U0001F4AC\U0001F510"
      deployment_environment: "\U0001F510\U0001F4ACplaceframe-secrets_DEPLOYMENT_ENVIRONMENT\U0001F4AC\U0001F510"
      public_url: "\U0001F510\U0001F4ACplaceframe-secrets_PUBLIC_URL\U0001F4AC\U0001F510"
  placeframe-keycloak.default#placeframe-keycloak:
    guid: 219dc21a-09f7-4524-1832-8d0ea45c7c24
    type: placeframe-keycloak
    class: default
    id: placeframe-keycloak
    metadata: {}
    params: {}
    source_workload: api
    provisioner: template://placeframe/keycloak-k8s
    state:
      realm: placeframe-dev
      service: keycloak
    outputs:
      certs_url: http://keycloak:8080/realms/placeframe-dev/protocol/openid-connect/certs
  placeframe-postgres.default#placeframe-db:
    guid: 549ddbdb-02db-4b39-1467-524ba30e6bd1
    type: placeframe-postgres
    class: default
    id: placeframe-db
    metadata: {}
    params: {}
    source_workload: api
    provisioner: template://placeframe/postgres-k8s
    state:
      dbName: placeframe
      service: pf-postgres
    outputs:
      api_password: "\U0001F510\U0001F4ACplaceframe-secrets_DATABASE_API_USER_PASSWORD\U0001F4AC\U0001F510"
      api_username: placeframe_api_user
      auth_password: "\U0001F510\U0001F4ACplaceframe-secrets_DATABASE_AUTH_USER_PASSWORD\U0001F4AC\U0001F510"
      auth_username: placeframe_auth_user
      host: pf-postgres
      name: placeframe
      orchestration_password: "\U0001F510\U0001F4ACplaceframe-secrets_DATABASE_ORCHESTRATION_USER_PASSWORD\U0001F4AC\U0001F510"
      orchestration_username: placeframe_orchestration_user
      owner_username: placeframe_owner
      port: 5432
  s3.default#placeframe-bucket:
    guid: b55a0d9d-5961-4000-8859-ef02c97dd898
    type: s3
    class: default
    id: placeframe-bucket
    metadata: {}
    params: {}
    source_workload: api
    provisioner: template://placeframe/seaweedfs-k8s
    state:
      bucket: dev-reconstructions
      capturesBucket: dev-captures
      service: seaweedfs
    outputs:
      access_key_id: "\U0001F510\U0001F4ACplaceframe-secrets_S3_ACCESS_KEY\U0001F4AC\U0001F510"
      bucket: dev-reconstructions
      endpoint: http://seaweedfs:8333
      secret_key: "\U0001F510\U0001F4ACplaceframe-secrets_S3_SECRET_KEY\U0001F4AC\U0001F510"
shared_state: {}
patching_templates: []
