apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: placeframe
  labels:
    com.docker.compose.project: placeframe
    com.docker.compose.service: alloy
spec:
  selector:
    com.docker.compose.project: placeframe
    com.docker.compose.service: alloy
  ports:
  - name: alloy-4317
    port: 4317
    targetPort: alloy-4317
