apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver-published
  namespace: placeframe
  labels:
    com.docker.compose.project: placeframe
    com.docker.compose.service: cloudbeaver
spec:
  selector:
    com.docker.compose.project: placeframe
    com.docker.compose.service: cloudbeaver
  ports:
  - name: cloudbeav-58978
    port: 58978
    protocol: TCP
    targetPort: cloudbeave-8978
