apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver
  namespace: placeframe
  labels:
    com.docker.compose.project: placeframe
    com.docker.compose.service: cloudbeaver
spec:
  selector:
    com.docker.compose.project: placeframe
    com.docker.compose.service: cloudbeaver
  ports:
  - name: cloudbeave-8978
    port: 8978
    targetPort: cloudbeave-8978
