apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: placeframe
  labels:
    com.docker.compose.project: placeframe
    com.docker.compose.service: gateway
spec:
  selector:
    com.docker.compose.project: placeframe
    com.docker.compose.service: gateway
  ports:
  - name: gateway-80
    port: 80
    targetPort: gateway-80
  - name: gateway-443
    port: 443
    targetPort: gateway-443
  - name: gateway-2019
    port: 2019
    targetPort: gateway-2019
  - name: gateway-8443
    port: 8443
    targetPort: gateway-8443
