apiVersion: v1
kind: Service
metadata:
  name: grafana-published
  namespace: placeframe
  labels:
    com.docker.compose.project: placeframe
    com.docker.compose.service: grafana
spec:
  selector:
    com.docker.compose.project: placeframe
    com.docker.compose.service: grafana
  ports:
  - name: grafana-53000
    port: 53000
    protocol: TCP
    targetPort: grafana-3000
