apiVersion: v1
kind: Service
metadata:
  name: initialize-loki
  namespace: placeframe
  labels:
    com.docker.compose.project: placeframe
    com.docker.compose.service: initialize-loki
spec:
  selector:
    com.docker.compose.project: placeframe
    com.docker.compose.service: initialize-loki
  ports:
  - name: initialize-3100
    port: 3100
    targetPort: initialize-3100
