apiVersion: v1
kind: Service
metadata:
  name: minio-published
  namespace: placeframe
  labels:
    com.docker.compose.project: placeframe
    com.docker.compose.service: minio
spec:
  selector:
    com.docker.compose.project: placeframe
    com.docker.compose.service: minio
  ports:
  - name: minio-59001
    port: 59001
    protocol: TCP
    targetPort: minio-9001
