services:
  reconstructor-cuda:
    image: "ghcr.io/outernet-foundation/placeframe/reconstructor-cuda:${RECONSTRUCTOR_SHA:?err}"
    depends_on:
      lease-server:
        condition: service_healthy
    restart: on-failure
    expose:
      - "5678"
    gpus: all
    environment:
      LEASE_SERVER_URL: http://lease-server:8000
      MINIO_ENDPOINT_URL: "http://minio:9000"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:?err}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:?err}"
      RECONSTRUCTIONS_BUCKET: dev-reconstructions
      CAPTURES_BUCKET: dev-captures

  localizer-cuda:
    image: "ghcr.io/outernet-foundation/placeframe/localizer-cuda:${LOCALIZER_SHA:?err}"
    expose:
      - "8000"
    networks:
      default:
        aliases: [ "localizer" ]
    gpus: all
    environment:
      MINIO_ENDPOINT_URL: "http://minio:9000"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:?err}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:?err}"
      RECONSTRUCTIONS_BUCKET: dev-reconstructions
