services:
  reconstructor-rocm:
    image: "ghcr.io/outernet-foundation/placeframe/reconstructor-rocm:${RECONSTRUCTOR_SHA:?err}"
    depends_on:
      lease-server:
        condition: service_healthy
    restart: on-failure
    expose:
      - "5678" # debug port
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - 44
      - 110
    environment:
      LEASE_SERVER_URL: http://lease-server:8000
      MINIO_ENDPOINT_URL: "http://minio:9000"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:?err}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:?err}"
      RECONSTRUCTIONS_BUCKET: dev-reconstructions
      CAPTURES_BUCKET: dev-captures

  localizer-rocm:
    image: "ghcr.io/outernet-foundation/placeframe/localizer-rocm:${LOCALIZER_SHA:?err}"
    expose:
      - "8000"
    networks:
      default:
        aliases: [ "localizer" ]
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - 44
      - 110
    environment:
      MINIO_ENDPOINT_URL: "http://minio:9000"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:?err}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:?err}"
      RECONSTRUCTIONS_BUCKET: dev-reconstructions
