/*
 * Plerion API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = PlerionClient.Client.OpenAPIDateConverter;

namespace PlerionClient.Model
{
    /// <summary>
    /// BodyCreateCaptre
    /// </summary>
    [DataContract(Name = "Body_create_captre")]
    public partial class BodyCreateCaptre
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BodyCreateCaptre" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BodyCreateCaptre() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BodyCreateCaptre" /> class.
        /// </summary>
        /// <param name="filename">filename (required).</param>
        public BodyCreateCaptre(string filename = default)
        {
            // to ensure "filename" is required (not null)
            if (filename == null)
            {
                throw new ArgumentNullException("filename is a required property for BodyCreateCaptre and cannot be null");
            }
            this.Filename = filename;
        }

        /// <summary>
        /// Gets or Sets Filename
        /// </summary>
        [DataMember(Name = "filename", IsRequired = true, EmitDefaultValue = true)]
        public string Filename { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BodyCreateCaptre {\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
