/*
 * Plerion
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = PlerionClient.Client.FileParameter;
using OpenAPIDateConverter = PlerionClient.Client.OpenAPIDateConverter;

namespace PlerionClient.Model
{
    // fuck
    /// <summary>
    /// ReconstructionOptions
    /// </summary>
    [DataContract(Name = "ReconstructionOptions")]
    public partial class ReconstructionOptions
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReconstructionOptions" /> class.
        /// </summary>
        /// <param name="neightborsCount">neightborsCount.</param>
        /// <param name="maxKeypointsPerImage">maxKeypointsPerImage.</param>
        /// <param name="ransacMaxError">ransacMaxError.</param>
        /// <param name="ransacMinInlierRatio">ransacMinInlierRatio.</param>
        /// <param name="usePriorPosition">usePriorPosition.</param>
        /// <param name="triangulationMinimumAngle">triangulationMinimumAngle.</param>
        /// <param name="triangulationCompleteMaxReprojectionError">triangulationCompleteMaxReprojectionError.</param>
        /// <param name="triangulationMergeMaxReprojectionError">triangulationMergeMaxReprojectionError.</param>
        /// <param name="mapperFilterMaxReprojectionError">mapperFilterMaxReprojectionError.</param>
        /// <param name="bundleAdjustmentRefineSensorFromRig">bundleAdjustmentRefineSensorFromRig.</param>
        /// <param name="bundleAdjustmentRefineFocalLength">bundleAdjustmentRefineFocalLength.</param>
        /// <param name="bundleAdjustmentRefinePrincipalPoint">bundleAdjustmentRefinePrincipalPoint.</param>
        /// <param name="bundleAdjustmentRefineAdditionalParams">bundleAdjustmentRefineAdditionalParams.</param>
        public ReconstructionOptions()
        {
        }

        /// <summary>
        /// Gets or Sets NeightborsCount
        /// </summary>
        [DataMember(Name = "neightbors_count", EmitDefaultValue = true)]
        public int? NeightborsCount
        {
            get{ return _NeightborsCount;}
            set
            {
                _NeightborsCount = value;
                _flagNeightborsCount = true;
            }
        }
        private int? _NeightborsCount;
        private bool _flagNeightborsCount;

        /// <summary>
        /// Returns false as NeightborsCount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNeightborsCount()
        {
            return _flagNeightborsCount;
        }
        /// <summary>
        /// Gets or Sets MaxKeypointsPerImage
        /// </summary>
        [DataMember(Name = "max_keypoints_per_image", EmitDefaultValue = true)]
        public int? MaxKeypointsPerImage
        {
            get{ return _MaxKeypointsPerImage;}
            set
            {
                _MaxKeypointsPerImage = value;
                _flagMaxKeypointsPerImage = true;
            }
        }
        private int? _MaxKeypointsPerImage;
        private bool _flagMaxKeypointsPerImage;

        /// <summary>
        /// Returns false as MaxKeypointsPerImage should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMaxKeypointsPerImage()
        {
            return _flagMaxKeypointsPerImage;
        }
        /// <summary>
        /// Gets or Sets RansacMaxError
        /// </summary>
        [DataMember(Name = "ransac_max_error", EmitDefaultValue = true)]
        public double? RansacMaxError
        {
            get{ return _RansacMaxError;}
            set
            {
                _RansacMaxError = value;
                _flagRansacMaxError = true;
            }
        }
        private double? _RansacMaxError;
        private bool _flagRansacMaxError;

        /// <summary>
        /// Returns false as RansacMaxError should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRansacMaxError()
        {
            return _flagRansacMaxError;
        }
        /// <summary>
        /// Gets or Sets RansacMinInlierRatio
        /// </summary>
        [DataMember(Name = "ransac_min_inlier_ratio", EmitDefaultValue = true)]
        public double? RansacMinInlierRatio
        {
            get{ return _RansacMinInlierRatio;}
            set
            {
                _RansacMinInlierRatio = value;
                _flagRansacMinInlierRatio = true;
            }
        }
        private double? _RansacMinInlierRatio;
        private bool _flagRansacMinInlierRatio;

        /// <summary>
        /// Returns false as RansacMinInlierRatio should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRansacMinInlierRatio()
        {
            return _flagRansacMinInlierRatio;
        }
        /// <summary>
        /// Gets or Sets UsePriorPosition
        /// </summary>
        [DataMember(Name = "use_prior_position", EmitDefaultValue = true)]
        public bool? UsePriorPosition
        {
            get{ return _UsePriorPosition;}
            set
            {
                _UsePriorPosition = value;
                _flagUsePriorPosition = true;
            }
        }
        private bool? _UsePriorPosition;
        private bool _flagUsePriorPosition;

        /// <summary>
        /// Returns false as UsePriorPosition should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeUsePriorPosition()
        {
            return _flagUsePriorPosition;
        }
        /// <summary>
        /// Gets or Sets TriangulationMinimumAngle
        /// </summary>
        [DataMember(Name = "triangulation_minimum_angle", EmitDefaultValue = true)]
        public double? TriangulationMinimumAngle
        {
            get{ return _TriangulationMinimumAngle;}
            set
            {
                _TriangulationMinimumAngle = value;
                _flagTriangulationMinimumAngle = true;
            }
        }
        private double? _TriangulationMinimumAngle;
        private bool _flagTriangulationMinimumAngle;

        /// <summary>
        /// Returns false as TriangulationMinimumAngle should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTriangulationMinimumAngle()
        {
            return _flagTriangulationMinimumAngle;
        }
        /// <summary>
        /// Gets or Sets TriangulationCompleteMaxReprojectionError
        /// </summary>
        [DataMember(Name = "triangulation_complete_max_reprojection_error", EmitDefaultValue = true)]
        public double? TriangulationCompleteMaxReprojectionError
        {
            get{ return _TriangulationCompleteMaxReprojectionError;}
            set
            {
                _TriangulationCompleteMaxReprojectionError = value;
                _flagTriangulationCompleteMaxReprojectionError = true;
            }
        }
        private double? _TriangulationCompleteMaxReprojectionError;
        private bool _flagTriangulationCompleteMaxReprojectionError;

        /// <summary>
        /// Returns false as TriangulationCompleteMaxReprojectionError should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTriangulationCompleteMaxReprojectionError()
        {
            return _flagTriangulationCompleteMaxReprojectionError;
        }
        /// <summary>
        /// Gets or Sets TriangulationMergeMaxReprojectionError
        /// </summary>
        [DataMember(Name = "triangulation_merge_max_reprojection_error", EmitDefaultValue = true)]
        public double? TriangulationMergeMaxReprojectionError
        {
            get{ return _TriangulationMergeMaxReprojectionError;}
            set
            {
                _TriangulationMergeMaxReprojectionError = value;
                _flagTriangulationMergeMaxReprojectionError = true;
            }
        }
        private double? _TriangulationMergeMaxReprojectionError;
        private bool _flagTriangulationMergeMaxReprojectionError;

        /// <summary>
        /// Returns false as TriangulationMergeMaxReprojectionError should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTriangulationMergeMaxReprojectionError()
        {
            return _flagTriangulationMergeMaxReprojectionError;
        }
        /// <summary>
        /// Gets or Sets MapperFilterMaxReprojectionError
        /// </summary>
        [DataMember(Name = "mapper_filter_max_reprojection_error", EmitDefaultValue = true)]
        public double? MapperFilterMaxReprojectionError
        {
            get{ return _MapperFilterMaxReprojectionError;}
            set
            {
                _MapperFilterMaxReprojectionError = value;
                _flagMapperFilterMaxReprojectionError = true;
            }
        }
        private double? _MapperFilterMaxReprojectionError;
        private bool _flagMapperFilterMaxReprojectionError;

        /// <summary>
        /// Returns false as MapperFilterMaxReprojectionError should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMapperFilterMaxReprojectionError()
        {
            return _flagMapperFilterMaxReprojectionError;
        }
        /// <summary>
        /// Gets or Sets BundleAdjustmentRefineSensorFromRig
        /// </summary>
        [DataMember(Name = "bundle_adjustment_refine_sensor_from_rig", EmitDefaultValue = true)]
        public bool? BundleAdjustmentRefineSensorFromRig
        {
            get{ return _BundleAdjustmentRefineSensorFromRig;}
            set
            {
                _BundleAdjustmentRefineSensorFromRig = value;
                _flagBundleAdjustmentRefineSensorFromRig = true;
            }
        }
        private bool? _BundleAdjustmentRefineSensorFromRig;
        private bool _flagBundleAdjustmentRefineSensorFromRig;

        /// <summary>
        /// Returns false as BundleAdjustmentRefineSensorFromRig should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeBundleAdjustmentRefineSensorFromRig()
        {
            return _flagBundleAdjustmentRefineSensorFromRig;
        }
        /// <summary>
        /// Gets or Sets BundleAdjustmentRefineFocalLength
        /// </summary>
        [DataMember(Name = "bundle_adjustment_refine_focal_length", EmitDefaultValue = true)]
        public bool? BundleAdjustmentRefineFocalLength
        {
            get{ return _BundleAdjustmentRefineFocalLength;}
            set
            {
                _BundleAdjustmentRefineFocalLength = value;
                _flagBundleAdjustmentRefineFocalLength = true;
            }
        }
        private bool? _BundleAdjustmentRefineFocalLength;
        private bool _flagBundleAdjustmentRefineFocalLength;

        /// <summary>
        /// Returns false as BundleAdjustmentRefineFocalLength should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeBundleAdjustmentRefineFocalLength()
        {
            return _flagBundleAdjustmentRefineFocalLength;
        }
        /// <summary>
        /// Gets or Sets BundleAdjustmentRefinePrincipalPoint
        /// </summary>
        [DataMember(Name = "bundle_adjustment_refine_principal_point", EmitDefaultValue = true)]
        public bool? BundleAdjustmentRefinePrincipalPoint
        {
            get{ return _BundleAdjustmentRefinePrincipalPoint;}
            set
            {
                _BundleAdjustmentRefinePrincipalPoint = value;
                _flagBundleAdjustmentRefinePrincipalPoint = true;
            }
        }
        private bool? _BundleAdjustmentRefinePrincipalPoint;
        private bool _flagBundleAdjustmentRefinePrincipalPoint;

        /// <summary>
        /// Returns false as BundleAdjustmentRefinePrincipalPoint should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeBundleAdjustmentRefinePrincipalPoint()
        {
            return _flagBundleAdjustmentRefinePrincipalPoint;
        }
        /// <summary>
        /// Gets or Sets BundleAdjustmentRefineAdditionalParams
        /// </summary>
        [DataMember(Name = "bundle_adjustment_refine_additional_params", EmitDefaultValue = true)]
        public bool? BundleAdjustmentRefineAdditionalParams
        {
            get{ return _BundleAdjustmentRefineAdditionalParams;}
            set
            {
                _BundleAdjustmentRefineAdditionalParams = value;
                _flagBundleAdjustmentRefineAdditionalParams = true;
            }
        }
        private bool? _BundleAdjustmentRefineAdditionalParams;
        private bool _flagBundleAdjustmentRefineAdditionalParams;

        /// <summary>
        /// Returns false as BundleAdjustmentRefineAdditionalParams should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeBundleAdjustmentRefineAdditionalParams()
        {
            return _flagBundleAdjustmentRefineAdditionalParams;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReconstructionOptions {\n");
            sb.Append("  NeightborsCount: ").Append(NeightborsCount).Append("\n");
            sb.Append("  MaxKeypointsPerImage: ").Append(MaxKeypointsPerImage).Append("\n");
            sb.Append("  RansacMaxError: ").Append(RansacMaxError).Append("\n");
            sb.Append("  RansacMinInlierRatio: ").Append(RansacMinInlierRatio).Append("\n");
            sb.Append("  UsePriorPosition: ").Append(UsePriorPosition).Append("\n");
            sb.Append("  TriangulationMinimumAngle: ").Append(TriangulationMinimumAngle).Append("\n");
            sb.Append("  TriangulationCompleteMaxReprojectionError: ").Append(TriangulationCompleteMaxReprojectionError).Append("\n");
            sb.Append("  TriangulationMergeMaxReprojectionError: ").Append(TriangulationMergeMaxReprojectionError).Append("\n");
            sb.Append("  MapperFilterMaxReprojectionError: ").Append(MapperFilterMaxReprojectionError).Append("\n");
            sb.Append("  BundleAdjustmentRefineSensorFromRig: ").Append(BundleAdjustmentRefineSensorFromRig).Append("\n");
            sb.Append("  BundleAdjustmentRefineFocalLength: ").Append(BundleAdjustmentRefineFocalLength).Append("\n");
            sb.Append("  BundleAdjustmentRefinePrincipalPoint: ").Append(BundleAdjustmentRefinePrincipalPoint).Append("\n");
            sb.Append("  BundleAdjustmentRefineAdditionalParams: ").Append(BundleAdjustmentRefineAdditionalParams).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
