/*
 * Plerion
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = PlerionClient.Client.FileParameter;
using OpenAPIDateConverter = PlerionClient.Client.OpenAPIDateConverter;

namespace PlerionClient.Model
{
    // fuck
    /// <summary>
    /// ReconstructionOptions
    /// </summary>
    [DataContract(Name = "ReconstructionOptions")]
    public partial class ReconstructionOptions
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReconstructionOptions" /> class.
        /// </summary>
        /// <param name="neightborsCount">neightborsCount.</param>
        /// <param name="maxKeypointsPerImage">maxKeypointsPerImage.</param>
        /// <param name="usePriorPosition">usePriorPosition.</param>
        /// <param name="baRefineSensorFromRig">baRefineSensorFromRig.</param>
        /// <param name="baRefineFocalLength">baRefineFocalLength.</param>
        /// <param name="baRefinePrincipalPoint">baRefinePrincipalPoint.</param>
        /// <param name="baRefineExtraParams">baRefineExtraParams.</param>
        public ReconstructionOptions()
        {
        }

        /// <summary>
        /// Gets or Sets NeightborsCount
        /// </summary>
        [DataMember(Name = "neightbors_count", EmitDefaultValue = true)]
        public int? NeightborsCount
        {
            get{ return _NeightborsCount;}
            set
            {
                _NeightborsCount = value;
                _flagNeightborsCount = true;
            }
        }
        private int? _NeightborsCount;
        private bool _flagNeightborsCount;

        /// <summary>
        /// Returns false as NeightborsCount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNeightborsCount()
        {
            return _flagNeightborsCount;
        }
        /// <summary>
        /// Gets or Sets MaxKeypointsPerImage
        /// </summary>
        [DataMember(Name = "max_keypoints_per_image", EmitDefaultValue = true)]
        public int? MaxKeypointsPerImage
        {
            get{ return _MaxKeypointsPerImage;}
            set
            {
                _MaxKeypointsPerImage = value;
                _flagMaxKeypointsPerImage = true;
            }
        }
        private int? _MaxKeypointsPerImage;
        private bool _flagMaxKeypointsPerImage;

        /// <summary>
        /// Returns false as MaxKeypointsPerImage should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMaxKeypointsPerImage()
        {
            return _flagMaxKeypointsPerImage;
        }
        /// <summary>
        /// Gets or Sets UsePriorPosition
        /// </summary>
        [DataMember(Name = "use_prior_position", EmitDefaultValue = true)]
        public bool? UsePriorPosition
        {
            get{ return _UsePriorPosition;}
            set
            {
                _UsePriorPosition = value;
                _flagUsePriorPosition = true;
            }
        }
        private bool? _UsePriorPosition;
        private bool _flagUsePriorPosition;

        /// <summary>
        /// Returns false as UsePriorPosition should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeUsePriorPosition()
        {
            return _flagUsePriorPosition;
        }
        /// <summary>
        /// Gets or Sets BaRefineSensorFromRig
        /// </summary>
        [DataMember(Name = "ba_refine_sensor_from_rig", EmitDefaultValue = true)]
        public bool? BaRefineSensorFromRig
        {
            get{ return _BaRefineSensorFromRig;}
            set
            {
                _BaRefineSensorFromRig = value;
                _flagBaRefineSensorFromRig = true;
            }
        }
        private bool? _BaRefineSensorFromRig;
        private bool _flagBaRefineSensorFromRig;

        /// <summary>
        /// Returns false as BaRefineSensorFromRig should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeBaRefineSensorFromRig()
        {
            return _flagBaRefineSensorFromRig;
        }
        /// <summary>
        /// Gets or Sets BaRefineFocalLength
        /// </summary>
        [DataMember(Name = "ba_refine_focal_length", EmitDefaultValue = true)]
        public bool? BaRefineFocalLength
        {
            get{ return _BaRefineFocalLength;}
            set
            {
                _BaRefineFocalLength = value;
                _flagBaRefineFocalLength = true;
            }
        }
        private bool? _BaRefineFocalLength;
        private bool _flagBaRefineFocalLength;

        /// <summary>
        /// Returns false as BaRefineFocalLength should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeBaRefineFocalLength()
        {
            return _flagBaRefineFocalLength;
        }
        /// <summary>
        /// Gets or Sets BaRefinePrincipalPoint
        /// </summary>
        [DataMember(Name = "ba_refine_principal_point", EmitDefaultValue = true)]
        public bool? BaRefinePrincipalPoint
        {
            get{ return _BaRefinePrincipalPoint;}
            set
            {
                _BaRefinePrincipalPoint = value;
                _flagBaRefinePrincipalPoint = true;
            }
        }
        private bool? _BaRefinePrincipalPoint;
        private bool _flagBaRefinePrincipalPoint;

        /// <summary>
        /// Returns false as BaRefinePrincipalPoint should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeBaRefinePrincipalPoint()
        {
            return _flagBaRefinePrincipalPoint;
        }
        /// <summary>
        /// Gets or Sets BaRefineExtraParams
        /// </summary>
        [DataMember(Name = "ba_refine_extra_params", EmitDefaultValue = true)]
        public bool? BaRefineExtraParams
        {
            get{ return _BaRefineExtraParams;}
            set
            {
                _BaRefineExtraParams = value;
                _flagBaRefineExtraParams = true;
            }
        }
        private bool? _BaRefineExtraParams;
        private bool _flagBaRefineExtraParams;

        /// <summary>
        /// Returns false as BaRefineExtraParams should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeBaRefineExtraParams()
        {
            return _flagBaRefineExtraParams;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReconstructionOptions {\n");
            sb.Append("  NeightborsCount: ").Append(NeightborsCount).Append("\n");
            sb.Append("  MaxKeypointsPerImage: ").Append(MaxKeypointsPerImage).Append("\n");
            sb.Append("  UsePriorPosition: ").Append(UsePriorPosition).Append("\n");
            sb.Append("  BaRefineSensorFromRig: ").Append(BaRefineSensorFromRig).Append("\n");
            sb.Append("  BaRefineFocalLength: ").Append(BaRefineFocalLength).Append("\n");
            sb.Append("  BaRefinePrincipalPoint: ").Append(BaRefinePrincipalPoint).Append("\n");
            sb.Append("  BaRefineExtraParams: ").Append(BaRefineExtraParams).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
